baseURL = "https://vmc-project.github.io/"
#baseURL = ""
languageCode = "en-us"
title = "VMC"

# Change the default theme to be use when building the site with Hugo
theme = [ "vmc-theme", "hugo-theme-learn" ]

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

# Customization Parameters
[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  #themeVariant = "blue"
  #themeVariant = "green"
  themeVariant = "vmc"

# This tells Hugo where to create our HTML files from the content in our 
# publishDir = "ihrivnac.github.io" 

[[menu.shortcuts]] 
name = "<i class='fab fa-github'></i> vmc-project on Github"
identifier = "ds"
url = "https://github.com/vmc-project"
weight = 10

[[menu.shortcuts]] 
name = "<i class='far fa-copyright'></i> Copyright"
url = "/copyright"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30
